# Generated by Django 5.2.7 on 2025-10-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("STUDENT", "Student"), ("TEACHER", "Teacher")],
                default="STUDENT",
                max_length=10,
            ),
        ),
    ]
